### PR TITLE
rewrite arg parsing to use getopt()

### PR DESCRIPTION
**Pull request by crumbtoo**
very empty at the moment, but far more extensible than current impl.

### CODE REVIEW

**Comment by KevinAlavik** [comment]
@crumbtoo is there an way i could run
image
all tehse commands without an option in the begining just like tweak does it (idk how tweak does it)

**Comment by KevinAlavik** [comment]
@crumbtoo just wondering, do you have an discord that i can comunicate with you

**Comment by crumbtoo** [comment]
> @crumbtoo is there an way i could run
> 
> image
> 
> all tehse commands without an option in the begining just like tweak does it (idk how tweak does it)

can you give an example

**Comment by KevinAlavik** [comment]
> > @crumbtoo is there an way i could run
> > image
> > all tehse commands without an option in the begining just like tweak does it (idk how tweak does it)
> 
> can you give an example

i rust want to be able to run like: pie run, pie pico, pie update. And have the options after as sub commands like tweak does, that would work right?

**Comment by crumbtoo** [comment]
yes.

**Pull request merged**
